# Generated by Django 4.2.5 on 2023-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='google_doc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
