# Generated by Django 4.2.5 on 2023-09-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0004_remove_partner_id_alter_partner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
