# Generated by Django 5.0.4 on 2024-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partner_accept_fiat_partner_accept_pay_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='accept_fiat',
            new_name='accept_fiats',
        ),
    ]
