# Generated by Django 5.0.4 on 2024-05-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_rename_accept_fiat_partner_accept_fiats'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='google_sheet_name',
            field=models.CharField(default='Sheet1', help_text='google spreadsheet table name', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='google_doc_id',
            field=models.CharField(blank=True, help_text='google spreadsheet document id', max_length=100),
        ),
    ]
