# Generated by Django 4.2.5 on 2023-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('card', models.CharField(max_length=16)),
                ('payoutAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
