# Generated by Django 4.2.5 on 2023-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
