# Generated by Django 5.0.4 on 2024-05-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_rate'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='order',
            table_comment='income orders from partners',
        ),
    ]
