# Generated by Django 4.2.5 on 2023-09-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermodel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
    ]
