# Generated by Django 4.2.5 on 2023-09-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_remove_partner_id_alter_partner_user'),
        ('orders', '0008_order_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
