# Generated by Django 4.2.5 on 2023-09-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='callbackBody',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='callbackHeaders',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='callbackMethod',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='callbackUrl',
            field=models.TextField(default=''),
        ),
    ]
