# Generated by Django 4.2.5 on 2023-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_callbackbody_order_callbackheaders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='callbackBody',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='callbackHeaders',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='callbackMethod',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='callbackUrl',
            field=models.TextField(),
        ),
    ]
