# Generated by Django 5.0.4 on 2024-05-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='UAH, AUD, CHF, ...', max_length=128)),
            ],
            options={
                'db_table': 'fiat_currency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Binance, Bybit, WhiteBit,...', max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'market',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Binance, Bybit, WhiteBit,...', max_length=200)),
                ('description', models.TextField()),
                ('api_key', models.CharField(help_text='exchange market api key', max_length=300)),
                ('secret_key', models.CharField(help_text='exchange secret key', max_length=300)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
            options={
                'db_table': 'market_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Binance order pay type. Like Payeer, Bank of America, ...', max_length=128)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
            options={
                'db_table': 'pay_types',
                'ordering': ['name'],
            },
        ),
    ]
