# Generated by Django 5.0.4 on 2024-05-13 13:38

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketaccount',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True)),
        ),
        migrations.AlterField(
            model_name='marketaccount',
            name='secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True)),
        ),
    ]
