# Generated by Django 5.0.4 on 2024-05-27 19:11

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_marketaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketaccount',
            name='google_auth_qr_img',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default=None, null=True)),
        ),
    ]
