# Generated by Django 5.0.4 on 2024-05-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_monitors', '0001_initial'),
        ('markets', '0002_alter_marketaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.market'),
        ),
        migrations.AlterField(
            model_name='radar',
            name='fiat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.fiatcurrency'),
        ),
    ]
