# Generated by Django 5.0.4 on 2024-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_monitors', '0002_radar_market_alter_radar_fiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='tradeType',
            field=models.CharField(choices=[(1, 'BUY'), (2, 'SELL')], default='SELL', max_length=4),
        ),
    ]
