# Generated by Django 5.0.4 on 2024-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_monitors', '0003_radar_tradetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='tradeType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='SELL', max_length=4),
        ),
    ]
