# Generated by Django 5.0.4 on 2024-05-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_monitors', '0005_rename_paytype_radar_pay_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='transAmount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='the size of the amount in the order when searching for them on the market', max_digits=19),
        ),
    ]
