# Generated by Django 4.2.5 on 2023-09-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='rowNum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
